name: mealchooser
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: 
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner:
  readmore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"


flutter_icons:
 
  android: true
  ios: true
  flutter_lints: ^1.0.0
  provider:



flutter:


  uses-material-design: true
  assets:
    - image/